// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvUciRokKwOfNf4J-51UoehDzFwo6krq0',
    appId: '1:292797408774:web:7d4ffaffe2b46056288587',
    messagingSenderId: '292797408774',
    projectId: 'memorii-fe062',
    authDomain: 'memorii-fe062.firebaseapp.com',
    storageBucket: 'memorii-fe062.firebasestorage.app',
    measurementId: 'G-DFFB99G45L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYUHjtVHPJ0zwZwKl5c7AZduenPzDKcI',
    appId: '1:292797408774:android:c25d729d127b81a7288587',
    messagingSenderId: '292797408774',
    projectId: 'memorii-fe062',
    storageBucket: 'memorii-fe062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQjAS8Nbq07wP0leIkIQf2SV77ypDV3WM',
    appId: '1:292797408774:ios:49bbc91b6657638e288587',
    messagingSenderId: '292797408774',
    projectId: 'memorii-fe062',
    storageBucket: 'memorii-fe062.firebasestorage.app',
    iosBundleId: 'com.example.memorii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQjAS8Nbq07wP0leIkIQf2SV77ypDV3WM',
    appId: '1:292797408774:ios:49bbc91b6657638e288587',
    messagingSenderId: '292797408774',
    projectId: 'memorii-fe062',
    storageBucket: 'memorii-fe062.firebasestorage.app',
    iosBundleId: 'com.example.memorii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvUciRokKwOfNf4J-51UoehDzFwo6krq0',
    appId: '1:292797408774:web:d5b3a57a499dfcfa288587',
    messagingSenderId: '292797408774',
    projectId: 'memorii-fe062',
    authDomain: 'memorii-fe062.firebaseapp.com',
    storageBucket: 'memorii-fe062.firebasestorage.app',
    measurementId: 'G-ECFGF3TXB7',
  );
}
